{"date":"Wed Jun 26 2024 15:20:12 GMT+0530 (India Standard Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: something failed\nError: something failed\n    at Object.<anonymous> (C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js:9:7)\n    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n    at Module.load (node:internal/modules/cjs/loader:1208:32)\n    at Module._load (node:internal/modules/cjs/loader:1024:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)\n    at node:internal/main/run_main_module:28:49","os":{"loadavg":[0,0,0],"uptime":15020.937},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js"],"cwd":"C:\\Users\\account\\Desktop\\node\\demo-vidly","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":36508255,"external":38836881,"heapTotal":59645952,"heapUsed":40809816,"rss":81473536},"pid":8848,"uid":null,"version":"v20.14.0"},"stack":"Error: something failed\n    at Object.<anonymous> (C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js:9:7)\n    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n    at Module.load (node:internal/modules/cjs/loader:1208:32)\n    at Module._load (node:internal/modules/cjs/loader:1024:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)\n    at node:internal/main/run_main_module:28:49","trace":[{"column":7,"file":"C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js","function":null,"line":9,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1358,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1416,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1208,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1024,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":174,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":49,"file":"node:internal/main/run_main_module","function":null,"line":28,"method":null,"native":false}]}
{"date":"Wed Jun 26 2024 15:20:30 GMT+0530 (India Standard Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: something failed\nError: something failed\n    at Object.<anonymous> (C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js:9:7)\n    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n    at Module.load (node:internal/modules/cjs/loader:1208:32)\n    at Module._load (node:internal/modules/cjs/loader:1024:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)\n    at node:internal/main/run_main_module:28:49","os":{"loadavg":[0,0,0],"uptime":15039.187},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js"],"cwd":"C:\\Users\\account\\Desktop\\node\\demo-vidly","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":36508255,"external":38836881,"heapTotal":59645952,"heapUsed":41089088,"rss":81174528},"pid":8848,"uid":null,"version":"v20.14.0"},"stack":"Error: something failed\n    at Object.<anonymous> (C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js:9:7)\n    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n    at Module.load (node:internal/modules/cjs/loader:1208:32)\n    at Module._load (node:internal/modules/cjs/loader:1024:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)\n    at node:internal/main/run_main_module:28:49","trace":[{"column":7,"file":"C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js","function":null,"line":9,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1358,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1416,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1208,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1024,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":174,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":49,"file":"node:internal/main/run_main_module","function":null,"line":28,"method":null,"native":false}]}
{"date":"Wed Jun 26 2024 15:21:37 GMT+0530 (India Standard Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: Promise.reject is not a constructor\nTypeError: Promise.reject is not a constructor\n    at Object.<anonymous> (C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js:9:11)\n    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n    at Module.load (node:internal/modules/cjs/loader:1208:32)\n    at Module._load (node:internal/modules/cjs/loader:1024:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)\n    at node:internal/main/run_main_module:28:49","os":{"loadavg":[0,0,0],"uptime":15106.593},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js"],"cwd":"C:\\Users\\account\\Desktop\\node\\demo-vidly","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":36508255,"external":38836881,"heapTotal":59645952,"heapUsed":40163928,"rss":79986688},"pid":4912,"uid":null,"version":"v20.14.0"},"stack":"TypeError: Promise.reject is not a constructor\n    at Object.<anonymous> (C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js:9:11)\n    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n    at Module.load (node:internal/modules/cjs/loader:1208:32)\n    at Module._load (node:internal/modules/cjs/loader:1024:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)\n    at node:internal/main/run_main_module:28:49","trace":[{"column":11,"file":"C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js","function":null,"line":9,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1358,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1416,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1208,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1024,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":174,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":49,"file":"node:internal/main/run_main_module","function":null,"line":28,"method":null,"native":false}]}
{"date":"Wed Jun 26 2024 15:22:12 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"level":"error","message":"uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"promise rejected\".\nUnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"promise rejected\".","os":{"loadavg":[0,0,0],"uptime":15141.265},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js"],"cwd":"C:\\Users\\account\\Desktop\\node\\demo-vidly","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":36508255,"external":38856058,"heapTotal":59645952,"heapUsed":41495872,"rss":81600512},"pid":4848,"uid":null,"version":"v20.14.0"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"promise rejected\".","trace":[]}
{"date":"Wed Jun 26 2024 15:26:12 GMT+0530 (India Standard Time)","error":{"code":"ERR_UNHANDLED_REJECTION"},"exception":true,"level":"error","message":"uncaughtException: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"promise rejected\".\nUnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"promise rejected\".","os":{"loadavg":[0,0,0],"uptime":15381.546},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js"],"cwd":"C:\\Users\\account\\Desktop\\node\\demo-vidly","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":36508255,"external":38856058,"heapTotal":59908096,"heapUsed":40533184,"rss":81035264},"pid":10016,"uid":null,"version":"v20.14.0"},"stack":"UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"promise rejected\".","trace":[]}
{"date":"Wed Jun 26 2024 15:26:46 GMT+0530 (India Standard Time)","error":{},"exception":true,"level":"error","message":"uncaughtException: FATAL ERROR: jwtPrivateKey is not defined.\nError: FATAL ERROR: jwtPrivateKey is not defined.\n    at module.exports (C:\\Users\\account\\Desktop\\node\\demo-vidly\\startup\\config.js:5:15)\n    at Object.<anonymous> (C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js:7:28)\n    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n    at Module.load (node:internal/modules/cjs/loader:1208:32)\n    at Module._load (node:internal/modules/cjs/loader:1024:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)\n    at node:internal/main/run_main_module:28:49","os":{"loadavg":[0,0,0],"uptime":15415.328},"process":{"argv":["C:\\Program Files\\nodejs\\node.exe","C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js"],"cwd":"C:\\Users\\account\\Desktop\\node\\demo-vidly","execPath":"C:\\Program Files\\nodejs\\node.exe","gid":null,"memoryUsage":{"arrayBuffers":36508255,"external":38836881,"heapTotal":59645952,"heapUsed":41324880,"rss":81829888},"pid":7924,"uid":null,"version":"v20.14.0"},"stack":"Error: FATAL ERROR: jwtPrivateKey is not defined.\n    at module.exports (C:\\Users\\account\\Desktop\\node\\demo-vidly\\startup\\config.js:5:15)\n    at Object.<anonymous> (C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js:7:28)\n    at Module._compile (node:internal/modules/cjs/loader:1358:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)\n    at Module.load (node:internal/modules/cjs/loader:1208:32)\n    at Module._load (node:internal/modules/cjs/loader:1024:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)\n    at node:internal/main/run_main_module:28:49","trace":[{"column":15,"file":"C:\\Users\\account\\Desktop\\node\\demo-vidly\\startup\\config.js","function":"module.exports","line":5,"method":"exports","native":false},{"column":28,"file":"C:\\Users\\account\\Desktop\\node\\demo-vidly\\index.js","function":null,"line":7,"method":null,"native":false},{"column":14,"file":"node:internal/modules/cjs/loader","function":"Module._compile","line":1358,"method":"_compile","native":false},{"column":10,"file":"node:internal/modules/cjs/loader","function":"Module._extensions..js","line":1416,"method":".js","native":false},{"column":32,"file":"node:internal/modules/cjs/loader","function":"Module.load","line":1208,"method":"load","native":false},{"column":12,"file":"node:internal/modules/cjs/loader","function":"Module._load","line":1024,"method":"_load","native":false},{"column":12,"file":"node:internal/modules/run_main","function":"Function.executeUserEntryPoint [as runMain]","line":174,"method":"executeUserEntryPoint [as runMain]","native":false},{"column":49,"file":"node:internal/main/run_main_module","function":null,"line":28,"method":null,"native":false}]}
